name: Build docs

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    #if: github.repository == 'lvgl/lvgl'
    runs-on: ubuntu-latest

    steps:
      - name: ls dir
        run: |
          ls -al
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ""   # path to exclude separated by ,, ie: /dist/, /node_modules/


