name: Build docs

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    #if: github.repository == 'lvgl/lvgl'
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: rsync over ssh
        run: rsync ./* user@remote:/home/book/100ask_lvgl/tmp

